# Generated by Django 3.2.9 on 2021-11-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='menu_image',
            field=models.URLField(),
        ),
    ]
