# Generated by Django 3.2.9 on 2021-11-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0002_alter_beverage_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='rec_ice',
            field=models.CharField(max_length=80),
        ),
    ]
