# Generated by Django 3.2.9 on 2021-11-30 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0003_alter_beverage_rec_ice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychoice',
            name='ice',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mychoice',
            name='sugar',
            field=models.IntegerField(),
        ),
    ]
