# Generated by Django 3.2.9 on 2021-12-01 00:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0005_alter_mychoice_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='mychoice',
            name='topping_size',
            field=models.CharField(default=django.utils.timezone.now, max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beverage',
            name='rec_sugar',
            field=models.CharField(max_length=80),
        ),
    ]
