# Generated by Django 3.2.9 on 2021-12-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0007_alter_mychoice_sugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beverage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beverages', to='gongchas.category'),
        ),
        migrations.AlterField(
            model_name='mychoice',
            name='topping',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='mychoice',
            name='topping_size',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
