# Generated by Django 3.2.9 on 2021-12-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0009_auto_20211209_1749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyChoice',
        ),
    ]
