# Generated by Django 3.2.9 on 2021-12-09 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gongchas', '0010_delete_mychoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='current_time',
            new_name='order_date',
        ),
    ]
